### ISSUE TITLE
Create a PositionedObjectList class

### ISSUE THREAD

**Issue by vchelaru** [joelmartinez/flatredball-js#11]
Here's how it'd work in FRB:

Sprite sprite = new Sprite();
PositionedObjectList<Sprite> poList = new PositionedObjectList<Sprite>();

poList.Add(sprite);

if(poList.Contains(sprite)
{
  // this should be true
}

sprite.RemoveSelfFromListsBelongingTo();

if(poList.Contains(sprite)
{
  // this should be false
}

**Comment by joelmartinez** [comment]
Went to the base class and implemented attachable list ... https://github.com/joelmartinez/flatredball-js/wiki/AttachableList
